baseURL = "https://example.com/"
title = "GitHub Style"
googleAnalytics = "UA-123-456-789"
theme = "github-style"

[params]
  author = "yhnu"
  description = "yhnu's blog"
  github = "yhnu"
  twitter = "yhnu"
  email = "immb@qq.com"
  utterances = "example/example.github.io"
  avatar = "/images/avatar.png"
  url = "https://yhnu.github.io"