name: github pages

on:
  push:
    branches:
    - source

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      # with:
      #   submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    
    - name: Build
      run: |
        hugo --minify

    - name: Deploy
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: .
        # PUBLISH_DIR: ./public
        SCRIPT_MODE: true
      run: |
        # wget https://raw.githubusercontent.com/peaceiris/actions-gh-pages/v2/entrypoint.sh
        chmod +x entrypoint.sh
        bash ./entrypoint.sh

